GET http://localhost:3001/users/
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM2NTgwODM0Iiwicm9sIjoicmVmcmVzaFRva2VuIiwiaWF0IjoxNjE2NjQ2MzQ5fQ.fjxQfxFLiKe1La7SBf6kGTIRxWR0qZL0EX2v7sCj6ho
###

GET http://localhost:3001/categories

###
PUT http://localhost:3001/promote
content-type: application/json

{
    "id": "36580834",
    "rol": "admin"
}


